#!/usr/bin/env ruby
# frozen_string_literal: true

require 'bundler/inline'
require 'yaml'

gemfile do
  source 'https://rubygems.org'
  gem 'rushover'
  gem 'wombat'
end

BASE_URL = 'https://www.creality3dofficial.com'

config = YAML.load_file('config.yml')
pushover_enabled = config['pushover_enabled']
single_request_delay = config['single_request_delay'].to_f
group_request_delay = config['group_request_delay'].to_f

rushover = Rushover::Client.new(config['pushover_app_key']) if pushover_enabled

begin
  loop do
    config['creality_paths'].each do |creality_path|
      crawl_result = Wombat.crawl do
        base_url BASE_URL
        path creality_path

        product_name css: 'h1.product-single__title'
        add_to_cart_button xpath: '//button[@id="AddToCart-product-template"]'
      end
      sleep single_request_delay

      next if crawl_result['add_to_cart_button'] == 'Sold Out'

      message = "#{crawl_result['product_name']} is in stock at #{BASE_URL}#{creality_path}"
      puts message

      # Send push notification
      rushover.notify(config['pushover_user_key'], message) if pushover_enabled

      # Show Mac system notification
      system("osascript -e 'display notification \"#{message}\"'")
    end

    puts 'Sleeping...'
    sleep group_request_delay
  end
rescue Interrupt
  puts ''
end
